-- 可选单位数量：0 到 10
INSERT OR REPLACE INTO DomainValues (Domain, Value, Name, Description, SortIndex) VALUES
('RUIVO_UNIT_COUNT_DOMAIN', 0, '0', '0', 0),
('RUIVO_UNIT_COUNT_DOMAIN', 1, '1', '1', 10),
('RUIVO_UNIT_COUNT_DOMAIN', 2, '2', '2', 20),
('RUIVO_UNIT_COUNT_DOMAIN', 3, '3', '3', 30),
('RUIVO_UNIT_COUNT_DOMAIN', 4, '4', '4', 40),
('RUIVO_UNIT_COUNT_DOMAIN', 5, '5', '5', 50),
('RUIVO_UNIT_COUNT_DOMAIN', 6, '6', '6', 60),
('RUIVO_UNIT_COUNT_DOMAIN', 7, '7', '7', 70),
('RUIVO_UNIT_COUNT_DOMAIN', 8, '8', '8', 80),
('RUIVO_UNIT_COUNT_DOMAIN', 9, '9', '9', 90),
('RUIVO_UNIT_COUNT_DOMAIN', 10, '10', '10', 100);

-- 赠送对象：仅人类玩家或全部主要文明
INSERT OR REPLACE INTO DomainValues (Domain, Value, Name, Description, SortIndex) VALUES
('RUIVO_TARGET_PLAYERS_DOMAIN', 'HUMAN_ONLY', 'LOC_RUIVO_TARGET_HUMAN_ONLY_NAME', 'LOC_RUIVO_TARGET_HUMAN_ONLY_DESC', 0),
('RUIVO_TARGET_PLAYERS_DOMAIN', 'ALL_MAJOR', 'LOC_RUIVO_TARGET_ALL_MAJOR_NAME', 'LOC_RUIVO_TARGET_ALL_MAJOR_DESC', 10);

-- 时代限制：仅远古时代或任意开局时代
INSERT OR REPLACE INTO DomainValues (Domain, Value, Name, Description, SortIndex) VALUES
('RUIVO_ERA_LIMIT_DOMAIN', 'ANCIENT_ONLY', 'LOC_RUIVO_ERA_ANCIENT_ONLY_NAME', 'LOC_RUIVO_ERA_ANCIENT_ONLY_DESC', 0),
('RUIVO_ERA_LIMIT_DOMAIN', 'ANY_ERA', 'LOC_RUIVO_ERA_ANY_ERA_NAME', 'LOC_RUIVO_ERA_ANY_ERA_DESC', 10);

-- 高级设置参数
INSERT OR REPLACE INTO Parameters (ParameterId, Name, Description, Domain, DefaultValue, ConfigurationGroup, ConfigurationId, GroupId, SortIndex) VALUES
('RUIVO_TARGET_PLAYERS', 'LOC_RUIVO_TARGET_PLAYERS_NAME', 'LOC_RUIVO_TARGET_PLAYERS_DESC', 'RUIVO_TARGET_PLAYERS_DOMAIN', 'HUMAN_ONLY', 'Game', 'RUIVO_TARGET_PLAYERS', 'MapOptions', 1990),
('RUIVO_ERA_LIMIT', 'LOC_RUIVO_ERA_LIMIT_NAME', 'LOC_RUIVO_ERA_LIMIT_DESC', 'RUIVO_ERA_LIMIT_DOMAIN', 'ANCIENT_ONLY', 'Game', 'RUIVO_ERA_LIMIT', 'MapOptions', 1991),
('RUIVO_SETTLER_COUNT', 'LOC_RUIVO_SETTLER_COUNT_NAME', 'LOC_RUIVO_SETTLER_COUNT_DESC', 'RUIVO_UNIT_COUNT_DOMAIN', 1, 'Game', 'RUIVO_SETTLER_COUNT', 'MapOptions', 2000),
('RUIVO_WARRIOR_COUNT', 'LOC_RUIVO_WARRIOR_COUNT_NAME', 'LOC_RUIVO_WARRIOR_COUNT_DESC', 'RUIVO_UNIT_COUNT_DOMAIN', 3, 'Game', 'RUIVO_WARRIOR_COUNT', 'MapOptions', 2001),
('RUIVO_SCOUT_COUNT', 'LOC_RUIVO_SCOUT_COUNT_NAME', 'LOC_RUIVO_SCOUT_COUNT_DESC', 'RUIVO_UNIT_COUNT_DOMAIN', 1, 'Game', 'RUIVO_SCOUT_COUNT', 'MapOptions', 2002),
('RUIVO_BUILDER_COUNT', 'LOC_RUIVO_BUILDER_COUNT_NAME', 'LOC_RUIVO_BUILDER_COUNT_DESC', 'RUIVO_UNIT_COUNT_DOMAIN', 1, 'Game', 'RUIVO_BUILDER_COUNT', 'MapOptions', 2003),
('RUIVO_SLINGER_COUNT', 'LOC_RUIVO_SLINGER_COUNT_NAME', 'LOC_RUIVO_SLINGER_COUNT_DESC', 'RUIVO_UNIT_COUNT_DOMAIN', 0, 'Game', 'RUIVO_SLINGER_COUNT', 'MapOptions', 2004),
('RUIVO_TRADER_COUNT', 'LOC_RUIVO_TRADER_COUNT_NAME', 'LOC_RUIVO_TRADER_COUNT_DESC', 'RUIVO_UNIT_COUNT_DOMAIN', 0, 'Game', 'RUIVO_TRADER_COUNT', 'MapOptions', 2005);

